name: Deploy proserve-idp-aws-vpc
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build component
        run: npm run build
        
      - name: Deploy to Pulumi Registry
        run: |
          pulumi package publish --publisher bpiz --version ${{ github.sha }} .
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
